name: Libuid
version: '${version}'
main: dev.tako.libuid.LibuidPlugin
api-version: '1.21'
load: STARTUP
folia-supported: true
dependencies:
  server:
    CraftEngine:
      load: BEFORE
      required: true
      join-classpath: true
